- name: تحميل الاصدار
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: تأكيد نسخة Python
        run: |
          python --version
          which python
          pip --version

      - name: تحديث pip والمكتبات
        run: |
          python -m pip install --upgrade pip setuptools wheel

      - name: تحميل المتطلبات
        run: |
          if [ -f requirements.txt ]; then
            python -m pip install -r requirements.txt
          else
            echo "⚠️ لا يوجد ملف requirements.txt"
          fi
